version: '3.1'
services:
  mongo:
    image: mongo
    container_name: go_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - "./mongodb/data:/data/db"